version: '2'
services:
  app:
    image: yiisoftware/yii2-php:7.1-apache
    container_name: "books-app"
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./virtualhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - '8000:80'
    links:
      - db
  db:
    image: mysql:latest       
    container_name: "books-mysql"
    restart: always
    ports:
      - 3309:3306
    volumes:
      - ./.docker/database/mysql/data:/var/lib/mysql
      - ./mysql.conf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=books
      - MYSQL_USER=books
      - MYSQL_PASSWORD=books
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
